# Generated by Django 5.0.3 on 2024-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='cliente',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='estado_entrega',
            new_name='delivery_state',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='pago',
            new_name='pay',
        ),
        migrations.RemoveField(
            model_name='metodo_pago',
            name='company',
        ),
        migrations.AddField(
            model_name='ventas',
            name='total_mount',
            field=models.IntegerField(default=0),
        ),
    ]
