# Generated by Django 5.0.3 on 2024-12-01 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_cliente_ventas_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='customer',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='pay',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pago', to='ventas.estado_pago'),
        ),
    ]
