# Generated by Django 5.0.3 on 2024-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_ventas_customer_alter_ventas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='quantity_product',
            field=models.IntegerField(default=1),
        ),
    ]
