# Generated by Django 5.0.3 on 2024-12-05 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_detalle_venta_sale_alter_detalle_venta_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='total_mount',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='pago',
            name='pay_method',
            field=models.CharField(choices=[('EF', 'Efecetivo'), ('TF', 'Transferencia')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pay_status',
            field=models.CharField(choices=[('PAG', 'Pagado'), ('PEN', 'Pendiente'), ('CAN', 'Cancelado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pago',
            name='payed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='delivery_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_estado_entrega', to='ventas.estado_entrega'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pago', to='ventas.pago'),
        ),
    ]
