# Generated by Django 5.0.3 on 2024-12-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_rename_total_mount_ventas_total_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_Pago',
        ),
        migrations.DeleteModel(
            name='Metodo_Pago',
        ),
    ]
