# Generated by Django 5.0.3 on 2024-12-05 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_delete_estado_pago_delete_metodo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='total_amount',
            new_name='total_mount',
        ),
    ]
