# Generated by Django 5.0.3 on 2024-12-05 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_estado_pago_metodo_pago_alter_ventas_delivery_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='payed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='delivery_state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_estado_entrega', to='ventas.estado_entrega'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='pay',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pago', to='ventas.estado_pago'),
        ),
    ]
