# Generated by Django 5.0.3 on 2024-12-05 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_pago_payed_date_alter_ventas_delivery_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pay_status',
            field=models.CharField(choices=[('PAG', 'Pagado'), ('PEN', 'Pendiente')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='pay',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pago', to='ventas.pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pay_method',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TC', 'Tarjeta de Crédito'), ('TD', 'Tarjeta de Débito')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Estado_Pago',
        ),
        migrations.DeleteModel(
            name='Metodo_Pago',
        ),
    ]
