# Generated by Django 5.0.3 on 2024-12-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_pago_pay_status_alter_ventas_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_entrega',
            name='name',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En proceso'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pay_method',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TR', 'Transferencia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pay_status',
            field=models.CharField(choices=[('PAG', 'Pagado'), ('PEN', 'Pendiente'), ('CAN', 'Cancelado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='delivery_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_estado_entrega', to='ventas.estado_entrega'),
        ),
    ]
