# Generated by Django 5.0.3 on 2025-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_estado_entrega_name_alter_pago_pay_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_venta',
            name='quantity_product',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
