# Generated by Django 5.0.3 on 2025-01-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_ventas_observations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='detail',
            field=models.ManyToManyField(blank=True, related_name='ventas', to='ventas.detalle_venta'),
        ),
    ]
