# Generated by Django 5.0.3 on 2025-01-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_ventas_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='detail',
        ),
    ]
