# Generated by Django 5.0.3 on 2025-01-06 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_clientes_location'),
        ('ventas', '0016_remove_ventas_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_cliente', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_pago', to='ventas.pago'),
        ),
    ]
