# Generated by Django 5.0.3 on 2024-03-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='img',
            field=models.FilePathField(default='imgPath'),
        ),
        migrations.AddField(
            model_name='productos',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='quanty',
            field=models.IntegerField(default=1),
        ),
    ]
