# Generated by Django 5.0.3 on 2024-03-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_img_productos_price_productos_quanty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.FilePathField(default=0),
        ),
    ]
