# Generated by Django 5.0.3 on 2024-03-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='quanty',
            field=models.IntegerField(),
        ),
    ]
