# Generated by Django 5.0.3 on 2024-03-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_productos_img_alter_productos_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='img',
        ),
        migrations.AlterField(
            model_name='productos',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='quanty',
            field=models.IntegerField(default=1),
        ),
    ]
