# Generated by Django 5.0.3 on 2024-03-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_productos_img_alter_productos_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='img',
            field=models.FilePathField(default=0),
            preserve_default=False,
        ),
    ]
