# Generated by Django 5.0.3 on 2024-03-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_productos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.FileField(null=True, upload_to='imgs'),
        ),
    ]
