# Generated by Django 5.0.3 on 2024-03-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_productos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.CharField(default='path', max_length=200),
            preserve_default=False,
        ),
    ]
