# Generated by Django 5.0.3 on 2024-04-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_alter_productos_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
