# Generated by Django 5.0.3 on 2024-04-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_productos_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
