# Generated by Django 5.0.3 on 2024-04-10 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_alter_productos_publicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='publicado',
        ),
    ]
