# Generated by Django 5.0.3 on 2024-12-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_categorias_productos_published_alter_productos_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
