# Generated by Django 5.0.3 on 2025-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_alter_productos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.PositiveSmallIntegerField(default=False),
        ),
    ]
