# Generated by Django 5.0.3 on 2024-12-05 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='location',
        ),
    ]
